version: '2'
services:
  mongo:
    image: mongo
    ports:
      - "27027:27017"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    ports:
      - "9400:9200"
      - "9500:9300"
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - xpack.security.enabled=false
